---
namespace: abn-assessment

abnBackendApi:
  health_check:
    path: /health_check
  configMap:
    name: abn-backend-api-variables
    environment_variables:
      external_integration_url: "https://google.com"
  secrets:
    external_integration_secret_name: external-integration
  service:
    name: abn-backend-api
    port: 5000
    targetPort: 5000
  deployment:
    name: abn-backend-api
    replicas: 2
    image: abn-backend
    imagePullPolicy: Never
    containerPort: 5000

abnDataApi:
  service:
    name: abn-data-api
    port: 5000
    targetPort: 5000
  deployment:
    name: abn-data-api
    replicas: 2
    image: abn-data
    imagePullPolicy: Never
    containerPort: 5000
