---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.abnDataApi.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.abnDataApi.deployment.name }}
  ports:
    - protocol: "TCP"
      port: {{ .Values.abnDataApi.service.port }}
      targetPort: {{ .Values.abnDataApi.service.targetPort }}
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.abnDataApi.deployment.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.abnDataApi.deployment.name }}
  replicas: {{ .Values.abnDataApi.deployment.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.abnDataApi.deployment.name }}
    spec:
      containers:
        - name:  {{ .Values.abnDataApi.deployment.name }}
          image: {{ .Values.abnDataApi.deployment.image }}
          imagePullPolicy: {{ .Values.abnDataApi.deployment.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.abnDataApi.deployment.containerPort }}