---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.abnBackendApi.configMap.name }}
data:
  EXTERNAL_INTGERATION_URL: {{ .Values.abnBackendApi.configMap.environment_variables.external_integration_url }}