---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: abn-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - pathType: ImplementationSpecific
        path: /backend(/|$)(.*)
        backend:
          service:
            name: {{ .Values.abnBackendApi.service.name }}
            port:
              number: {{ .Values.abnBackendApi.service.port }}
      - pathType: ImplementationSpecific
        path: /data(/|$)(.*)
        backend:
          service:
            name: {{ .Values.abnDataApi.service.name }}
            port:
              number: {{ .Values.abnDataApi.service.port }}